version: '3.8'
services:
  web:
    container_name: web
    build:
      context: .
      target: dev
    restart: always
    # command: npm run dev
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=localuser
      - POSTGRES_PASSWORD=verysecurepassword
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data